if Mix.env() == :dev do
  defmodule Mix.Tasks.Graphene.Version.Generate do
    use Mix.Task
    require Logger

    @package_json_path Path.join(["assets", "package.json"])
    @versioning_path Path.join(["assets", "versioning.json"])
    @version_module_path Path.join(["lib", "graphene", "version.ex"])

    @deps_keys [
      {:carbon_web_components, "@carbon/web-components"},
      {:carbon_styles, "@carbon/styles"},
      {:ibm_products_web_components, "@carbon/ibm-products-web-components"},
      {:ibm_products_styles, "@carbon/ibm-products-styles"},
      {:ibm_plex, "@ibm/plex"}
    ]

    @range_keys [
      {:carbon_web_components_range, "carbon_web_components_range"},
      {:ibm_products_web_components_range, "ibm_products_web_components_range"}
    ]

    @impl true
    def run(_args \\ []) do
      Logger.debug("Running #{__MODULE__}")

      {graphene_version, versions} = read_versions!()
      ranges = read_ranges!()
      content = render_module(graphene_version, versions, ranges)

      File.mkdir_p!(Path.dirname(@version_module_path))
      File.write!(@version_module_path, content)
    end

    defp read_versions! do
      data =
        @package_json_path
        |> File.read!()
        |> Jason.decode!()

      graphene_version = Map.fetch!(data, "version")
      dependencies = Map.get(data, "dependencies", %{})
      dev_dependencies = Map.get(data, "devDependencies", %{})

      versions =
        Enum.reduce(@deps_keys, %{}, fn {key, dep_name}, acc ->
          version =
            Map.get(dependencies, dep_name) ||
              Map.get(dev_dependencies, dep_name) ||
              raise "Missing #{dep_name} in #{@package_json_path}"

          Map.put(acc, key, version)
        end)

      {graphene_version, versions}
    end

    defp read_ranges! do
      data =
        @versioning_path
        |> File.read!()
        |> Jason.decode!()

      Enum.reduce(@range_keys, %{}, fn {key, json_key}, acc ->
        Map.put(acc, key, Map.fetch!(data, json_key))
      end)
    end

    defp render_module(graphene_version, versions, ranges) do
      ordered_versions =
        Enum.map(@deps_keys, fn {key, _dep_name} ->
          {key, Map.fetch!(versions, key)}
        end)

      ordered_ranges =
        Enum.map(@range_keys, fn {key, _json_key} ->
          {key, Map.fetch!(ranges, key)}
        end)

      version_lines =
        ordered_versions
        |> Enum.map(fn {key, value} -> "  @#{key} #{inspect(value)}" end)
        |> Enum.join("\n")

      range_lines =
        ordered_ranges
        |> Enum.map(fn {key, value} -> "  @#{key} #{inspect(value)}" end)
        |> Enum.join("\n")

      function_lines =
        ordered_versions
        |> Enum.map(fn {key, _value} -> "  def #{key}, do: @#{key}" end)
        |> Enum.join("\n")

      range_function_lines =
        ordered_ranges
        |> Enum.map(fn {key, _value} -> "  def #{key}, do: @#{key}" end)
        |> Enum.join("\n")

      map_lines =
        (ordered_versions ++ ordered_ranges)
        |> Enum.map(fn {key, _value} -> "      #{key}: @#{key}," end)
        |> Enum.join("\n")

      """
      defmodule Graphene.Version do
        @moduledoc \"\"\"
        Autogenerated from assets/package.json. Do not edit directly.

        Run `mix graphene.version.generate` to refresh this file.
        \"\"\"

        @graphene #{inspect(graphene_version)}
      #{version_lines}
      #{range_lines}
        def graphene, do: @graphene
      #{function_lines}
      #{range_function_lines}
        def all do
          %{
            graphene: @graphene,
      #{map_lines}
          }
        end
      end
      """
    end
  end
end
