defmodule Graphene.Version do
  @moduledoc """
  Autogenerated from assets/package.json. Do not edit directly.

  Run `mix graphene.version.generate` to refresh this file.
  """

  @graphene "0.1.0"
  @carbon_web_components "2.48.0"
  @carbon_styles "^1.100.0"
  @ibm_products_web_components "^0.33.0"
  @ibm_products_styles "^2.80.0"
  @ibm_plex "^6.4.1"
  @carbon_web_components_range ">=2.48.0 <3.0.0"
  @ibm_products_web_components_range ">=0.33.0 <1.0.0"
  def graphene, do: @graphene
  def carbon_web_components, do: @carbon_web_components
  def carbon_styles, do: @carbon_styles
  def ibm_products_web_components, do: @ibm_products_web_components
  def ibm_products_styles, do: @ibm_products_styles
  def ibm_plex, do: @ibm_plex
  def carbon_web_components_range, do: @carbon_web_components_range
  def ibm_products_web_components_range, do: @ibm_products_web_components_range

  def all do
    %{
      graphene: @graphene,
      carbon_web_components: @carbon_web_components,
      carbon_styles: @carbon_styles,
      ibm_products_web_components: @ibm_products_web_components,
      ibm_products_styles: @ibm_products_styles,
      ibm_plex: @ibm_plex,
      carbon_web_components_range: @carbon_web_components_range,
      ibm_products_web_components_range: @ibm_products_web_components_range
    }
  end
end
